name: Build

on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8 for build
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@b173558d722b59b5f355e9cbd954ad3686b822d7
      with:
        arguments: build -x test
  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8 for test
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Test with Gradle
        uses: gradle/gradle-build-action@b173558d722b59b5f355e9cbd954ad3686b822d7
        with:
          arguments: test